import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class AnimalList here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class AnimalList extends World
{
    public String[] animals =
    {
        "ant",
        "armadillo",
        "baboon",
        "badger",
        "bat",
        "bear",
        "beaver",
        "beetle",
        "bobcat",
        "bull",
        "camel",
        "cat",
        "cheetah",
        "cow",
        "crab",
        "cricket",
        "crocodile",
        "crow",
        "deer",
        "dog",
        "dolphin",
        "duck",
        "eagle",
        "elephant",
        "fly",
        "frog",
        "fox",
        "goat",
        "goldfish",
        "goose",
        "gorilla",
        "hamster",
        "hawk",
        "hen",
        "horse",
        "hyena",
        "jaguar",
        "kangaroo",
        "leopard",
        "lion",
        "lizard",
        "lobster",
        "mole",
        "monkey",
        "mouse",
        "otter",
        "owl",
        "panther",
        "parrot",
        "pig",
        "pigeon",
        "puffin",
        "puma",
        "rabbit",
        "rat",
        "robin",
        "salmon",
        "seagull",
        "seal",
        "shark",
        "sheep",
        "shrimp",
        "snail",
        "snake",
        "spider",
        "swan",
        "swordfish",
        "tiger",
        "tuna",
        "turtle",
        "walrus",
        "wasp",
        "weasel",
        "whale",
        "wolf",
        "worm",
    };
    public AnimalList()
    {
        super(600,400,1);
    }
}
